name: Go

on:
  push:
    tags:
      - "*.*.**"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: WillAbides/setup-go-faster@v1
        with:
          go-version: 1.16rc1
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Install gox
        run: |
          go get github.com/mitchellh/gox
          go install github.com/mitchellh/gox

      - name: Test
        run: go test -v ./...

      - name: Build
        run: |
          ./build.sh

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          files: |
            out/goloc.zip
